package com.example.jobSite.enums;

public enum Position {
    SOFTWARE_ENGINEER,
    FRONTEND_DEVELOPER,
    BACKEND_DEVELOPER,
    FULL_STACK_DEVELOPER,
    MOBILE_APP_DEVELOPER,
    GAME_DEVELOPER,
    DATABASE_ADMINISTRATOR,
    SYSTEMS_ADMINISTRATOR,
    NETWORK_ENGINEER,
    CLOUD_ARCHITECT,
    DATA_SCIENCE_ENGINEER,
    MACHINE_LEARNING_ENGINEER,
    ARTIFICIAL_INTELLIGENCE_ENGINEER,
    DEVOPS_ENGINEER,
    SECURITY_ENGINEER,
    QA_ENGINEER,
    TECHNICAL_WRITER,
    TECHNICAL_SUPPORT_ENGINEER
}